# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=230)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=12)),
                ('user_name', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
