# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_tasks',
            old_name='task_description',
            new_name='taskDescription',
        ),
        migrations.RenameField(
            model_name='daily_tasks',
            old_name='task_name',
            new_name='taskName',
        ),
        migrations.RenameField(
            model_name='daily_tasks',
            old_name='task_status',
            new_name='taskStatus',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='created_on',
            new_name='createdOn',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
    ]
