# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20170604_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=230)),
                ('taskDescription', models.TextField()),
                ('taskStatus', models.CharField(max_length=230)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Weekly_tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=230)),
                ('taskDescription', models.TextField()),
                ('taskStatus', models.CharField(max_length=230)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Users')),
            ],
        ),
        migrations.AddField(
            model_name='daily_tasks',
            name='user',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='testing.Users'),
        ),
    ]
