# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20170604_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
