# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20170605_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_tasks',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
