# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_auto_20170609_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='createdOn',
        ),
    ]
