# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_remove_users_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_tasks',
            name='taskCadence',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
