# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_daily_tasks_taskcadence'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_tasks',
            name='date',
            field=models.DateTimeField(default=datetime.date(2017, 6, 10)),
        ),
    ]
