# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_auto_20170610_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_tasks',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
