# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_daily_tasks_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_tasks',
            old_name='date',
            new_name='taskDate',
        ),
        migrations.RemoveField(
            model_name='daily_tasks',
            name='time',
        ),
        migrations.AlterField(
            model_name='daily_tasks',
            name='taskStatus',
            field=models.CharField(default=b'pending', max_length=10),
        ),
    ]
