# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_auto_20170611_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_tasks',
            name='taskDescription',
            field=models.TextField(default=b''),
        ),
    ]
