# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_auto_20170611_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_tasks',
            name='taskDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='daily_tasks',
            name='taskStatus',
            field=models.CharField(max_length=230),
        ),
    ]
