# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_auto_20170612_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_tasks',
            name='taskDate',
            field=models.CharField(max_length=20),
        ),
    ]
